# Generated by Django 4.0.5 on 2022-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='id_movie_tmdb',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='likes',
            name='id_movie',
            field=models.IntegerField(default=-1),
        ),
    ]
